server:
    port: 8090

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    data:
        mongodb:
            host: localhost
            port: 27090
            database: mihealth
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: mihealth

cache:
    timeToLiveSeconds: 3600
    hazelcast:
        debug: true
        stickySession: false
        backupCount: 1
